### ISSUE TITLE
[Todo] Add --system-sans

### ISSUE THREAD

**Issue by zaydek** [zaydek/duomo#146]
Idea is user does `--sans` ... `font-family: var(--sans), var(--system-sans)` or `--sans: xyz` and that will work.

**Comment by zaydek** [comment]
Added:

```scss
:root {
	--system-sans: font(sans);
	--system-serif: font(serif);
	--system-mono: font(mono);
}
```
