### ISSUE TITLE
[Todo] Implement prettier variant mixin

### ISSUE THREAD

**Issue by zaydek** [zaydek/duomo#164]
This is a pretty big job. We need to refactor how variants are implemented so that it’s much easier to write classes going forwards. A rough implementation looks like this:

```scss
@use "sass:string";

@function replace($str, $s1, $s2) {
    $n: string.index($str, $s1);
    @return string.slice($str, 1, $n - 1) + $s2 + string.slice($str, $n + string.length($s1));
}

@mixin variants($variants...) {
    @each $variant in $variants {
        @if $variant == core {
            @content;
        } @else if $variant == hover {
            @at-root {
                .hover\:#{string.slice("" + &, 2)}:hover {
                    @content;
                }
            }
        } @else if $variant == focus {
            @at-root {
                .focus\:#{string.slice("" + &, 2)}:focus {
                    @content;
                }
            }
        } @else if $variant == responsive {
            @at-root {
                .#{replace(string.slice("" + &, 2), "\\: .", "\\:")} {
                    @content;
                }
            }
        }
    }
}

$colors: (
    my-red: var(--my-red),
    my-blue: var(--my-blue),
    my-green: var(--my-green),
);

@mixin colors($variants...) {
    @each $k, $v in $colors {
        .#{$k} {
            @include variants($variants...) {
                background-color: $v;
            }
        }
    }
}

$breakpoints: (
    xs: 512,
    sm: 640,
    md: 768,
    lg: 1024,
    // 2xl: 1280,
);

@at-root {
    @include colors(core, hover, focus);
    @each $k, $v in $breakpoints {
        @media (min-width: $v + px) {
            .#{$k}\: {
                @include colors(responsive);
            }
        }
    }
}
```

After that, the library itself would need to be refactored and tested to make sure this works.
