### ISSUE TITLE
[Todo] Document multi-transition dark mode

### ISSUE THREAD

**Issue by zaydek** [zaydek/duomo#188]
```scss
@mixin to-dark-mode {
	:root[data-theme="dark"] & {
		$dur: 1200ms;
		$timing: timing(ease-out, $raw: true);
		transition: $dur background-color $timing, $dur border-color $timing;
	}
}
@mixin to-light-mode {
	:root:not([data-theme="dark"]) & {
		$dur: 600ms;
		$timing: timing(ease-out, $raw: true);
		transition: $dur background-color $timing, $dur border-color $timing;
	}
}

@mixin transitions {
	@include to-dark-mode;
	@include to-light-mode;
}
```
