### ISSUE TITLE
[Todo] Dark mode API

### ISSUE THREAD

**Issue by zaydek** [zaydek/duomo#189]
Probably something like this:

```scss
$light-map: (
	--bg-root: hsl(var(--gray-50)),
	--bg-search-app: hsl(var(--white)),
	--bg-search-app-content-search-bar: hsl(var(--white)),
	--bg-search-app-sidebar-preview: hsl(var(--white)),
	--bg-search-app-sidebar: hsl(var(--gray-50)),
	--bg-less-important: hsl(var(--gray-200)),
	--bg-important: hsl(var(--gray-300)),
	--bg-more-important: hsl(var(--gray-400)),
	--border-hr: hsl(var(--gray-200)),
);

$dark-map: (
	--bg-root: hsl(var(--gray-900)),
	--bg-search-app: hsl(var(--gray-800)),
	--bg-search-app-content-search-bar: hsl(var(--gray-800)),
	--bg-search-app-sidebar-preview: hsl(var(--gray-800)),
	--bg-search-app-sidebar: hsl(var(--gray-800)),
	--bg-less-important: hsl(var(--gray-700)),
	--bg-important: hsl(var(--gray-600)),
	--bg-more-important: hsl(var(--gray-500)),
	--border-hr: hsla(var(--gray-900)),
);
```

And then some includes to handle class generation. Also need to add transition somewhere to the equation, maybe simply as params or as an optional content block. Doing all of this in SCSS definitely feels right (as opposed to JS).

**Comment by zaydek** [comment]
This is a little too magical. Preferring raw SCSS / CSS variable-based approach for now.

**Comment by zaydek** [comment]
So this is probably a good idea depending on how we attack this. Basically we want something like this:

```scss

:root {
	--root-bg:                hsl(var(--gray-50));
	--app-bg:                 hsl(var(--white));
	--app-shadow:             0 0 0 1px hsl(var(--gray-200)), var(--shadow-xs), var(--shadow-md);
	--app-search-bar-bg:      hsl(var(--white));
	--app-sidebar-bg:         hsl(var(--gray-50));
	--app-sidebar-preview-bg: hsl(var(--white));
	--placeholder-bg-default: hsl(var(--gray-300));
	--border-color-default:   hsl(var(--gray-200));
}
[data-theme="dark"] {
	--root-bg:                hsl(var(--black));
	--app-bg:                 hsl(var(--gray-900));
	--app-shadow:             0 0 0 1px hsl(var(--gray-800)), var(--shadow-xs), var(--shadow-md);
	--app-search-bar-bg:      hsl(var(--gray-900));
	--app-sidebar-bg:         hsl(var(--gray-900));
	--app-sidebar-preview-bg: hsl(var(--gray-900));
	--placeholder-bg-default: hsl(var(--gray-700));
	--border-color-default:   hsl(var(--gray-800));
}
```

But modeled as a map. In theory there is enough information there to make it work. All we need to do is look at the names, map them to properties, and then create classes for for every collection of variable names and conditionally add `theme-transition`. We probably want to cover several edge cases such as `root-bg` and `border-color-default`. Note that we should also tweak theme-transition to support only decorative properties and not necessarily things like transform since that should probably not be animated between themes.

**Comment by zaydek** [comment]
It could be interesting if we add support for breakpoints, so in theory we can do `--app-shadow` and `--app-shadow-sm` and it just works. This is still not a layout concern which is why it’s not a terrible idea.

**Comment by zaydek** [comment]
This is a non-magical approach that seems to makes sense: https://codepen.io/zaydek/pen/JjROZLw?editors=1100.

Requires minimal CSS, namespace convention using classes (no data- attributes), transitions can be basically automatic, and still doesn’t require installation.

Weird one-off ideas can still be prototyping using Sass, so no concern there.

**Comment by zaydek** [comment]
This seems like the ideal API (when installed):

```scss
$light: (
	app-bg: color(white),
	app-shadow: 0 0 0 1px color(gray-200), shadow(xs), shadow(md),
	content-search-bar-bg: color(white),
	content-card-bg: color(white), // TODO
	sidebar-bg: color(white),
	sidebar-preview-bg: color(white),
	svg-color: color(black),
	svg-faded-color: color(black, 0.5),
);
$dark: (
	app-bg: color(white),
	app-shadow: 0 0 0 1px color(gray-200), shadow(xs), shadow(md),
	content-search-bar-bg: color(white),
	content-card-bg: color(white), // TODO
	sidebar-bg: color(white),
	sidebar-preview-bg: color(white),
	svg-color: color(black),
	svg-faded-color: color(black, 0.5),
);

@at-root {
	@include themes((
		light: $light,
		dark: $dark,
		duration: 400ms,
		timing: ease-out,
	));
}
```

Then if you need to do one-off styling you can still do like `[data-id="app"] { ... }`
