### ISSUE TITLE
[Todo] Implement new theming logic

### ISSUE THREAD

**Issue by zaydek** [zaydek/duomo#194]
The library would provide:

```scss
:root {
	--theme-transition: background-color var(--theme-duration) var(--theme-timing-function), border-color var(--theme-duration) var(--theme-timing-function), box-shadow var(--theme-duration) var(--theme-timing-function), color var(--theme-duration) var(--theme-timing-function), fill var(--theme-duration) var(--theme-timing-function), opacity var(--theme-duration) var(--theme-timing-function), stroke var(--theme-duration) var(--theme-timing-function), transform var(--theme-duration) var(--theme-timing-function);
}
```

And then default values for:

```scss
:root {
	--theme-duration: 700ms;
	--theme-timing-function: var(--ease-out);
}
```

In the introspection file. And then the user can override those two variables if needed.
