### ISSUE TITLE
[Todo] Add bg-placeholder

### ISSUE THREAD

**Issue by zaydek** [zaydek/duomo#196]
Add `bg-placeholder` to the library. In the introspection file it should also be provided a basic color to start.

```scss
.bg-placeholder {
  background-color: var(--placeholder-bg-default);
}
```

The placeholder variable itself should be `gray-200` or `gray-300` to start and if possible expose an alpha channel like: `--placeholder-bg-default: hsla(var(gray-200), var(--bg-opacity))`.

Then we can do stuff like: `bg-placeholder bg-opacity-50`.
