### ISSUE TITLE
[Todo] Breakpoint shorthand syntax

### ISSUE THREAD

**Issue by zaydek** [zaydek/duomo#229]
Want to have something like this:

```scss
@include sm {
	.bg-red-500 {
		background-color: red;
	}
}
```

**Comment by zaydek** [comment]
Hey Joy! Could you write a couple of mixins in https://www.sassmeister.com that do the following?

```scss
@include sm {
  // Put any code here
}
```

Builds this:

```scss
@media (min-width: 640px) {
  .sm {
    // Put any code here
  }
}
```

Can you try making that for `sm, md, lg, and xl`? The breakpoint sizes are `sm: 640, md: 768, lg: 1024`, and `xl: 1280`.

**Comment by zaydek** [comment]
This is our current progress

```scss
@use "sass:list";
@use "sass:map";
@use "sass:string";

$breakpoints: (
    sm: 640px,
    md: 768px,
    lg: 1024px,
    xl: 1028px,
);

@function breakpoint($key) {
    @return map.get($breakpoints, $key);
}

@mixin sm {
    @media (min-width: breakpoint(sm)) {
      @content;
    }
}

@mixin md {
    @media (min-width: breakpoint(md)) {
      @content;
    }
}

@mixin lg {
    @media (min-width: breakpoint(lg)) {
      @content;
    }
}

@mixin xl {
    @media (min-width: breakpoint(xl)) {
      @content;
    }
}

@function declass($selector) {
    @return string.slice("" + $selector, 2);
}

@mixin variants($variants...) {
    @at-root {
        & {
            @content;
        }
        @if list.index($variants, responsive) {
            $selector: declass(&);
            @include sm {
                .sm:#{$selector} {
                    @content;
                }
            }
            @include md {
                .md:#{$selector} {
                    @content;
                }
            }
            @include lg {
                .lg:#{$selector} {
                    @content;
                }
            }
            @include xl {
                .xl:#{$selector} {
                    @content;
                }
            }
        }
    }
}

.bg-red-500 {
    @include variants(responsive) {
        background-color: red;
    }
}

// @include sm {
//     .sm: {
//         &bg-red-500 {
//             background-color: red;
//         }
//     }
// }
```

**Comment by zaydek** [comment]
Here’s a revised implementation that is more expressive based on your work:

```scss
@use "sass:list";
@use "sass:map";
@use "sass:string";

$breakpoints: (
    sm: 640px,
    md: 768px,
    lg: 1024px,
    xl: 1028px,
);

@function breakpoint($key) {
    @return map.get($breakpoints, $key);
}

@mixin sm {
    @media (min-width: breakpoint(sm)) {
        .sm\: {
            @content;
        }
    }
}

@mixin md {
    @media (min-width: breakpoint(md)) {
        .md\: {
            @content;
        }
    }
}

@mixin lg {
    @media (min-width: breakpoint(lg)) {
        .lg\: {
            @content;
        }
    }
}

@mixin xl {
    @media (min-width: breakpoint(xl)) {
        .xl\: {
            @content;
        }
    }
}

@function declass($selector) {
    @return string.slice("" + $selector, 2);
}

@mixin variants($variants...) {
    @at-root {
        & {
            @content;
        }
        
        $selector: declass(&);
        @each $variant in $variants {
            @if $variant == sm or $variant == responsive {
                @include sm {
                    &#{$selector} {
                        @content;
                    }
                }
            }
            @if $variant == md or $variant == responsive {
                @include md {
                    &#{$selector} {
                        @content;
                    }
                }
            }
            @if $variant == lg or $variant == responsive {
                @include lg {
                    &#{$selector} {
                        @content;
                    }
                }
            }
            @if $variant == xl or $variant == responsive {
                @include xl {
                    &#{$selector} {
                        @content;
                    }
                }
            }
        }
    }
}

.bg-red-500 {
    @include variants(sm, md, lg) {
        background-color: red;
    }
}
```

The idea here is that we can use `@include variants(responsive)` or `@include variants(sm, md, lg)`, etc. depending on our needs. The code generation makes it possible for users to write normal Sass code how they need to, but leverage these mixins for composing responsive, etc. code.
