### ISSUE TITLE
[Todo] variants -> variant?

### ISSUE THREAD

**Issue by zaydek** [zaydek/duomo#233]

**Comment by zaydek** [comment]
See #164.

**Comment by zaydek** [comment]
See #229.

**Comment by zaydek** [comment]
So we can keep the name `variants` as is because what we want is slightly different. The current variants function is concerned with selector grouping, whereas what we want is the ability to compose how variant code is generated.

Here’s a MVP implementation based on previous / new work:

```scss
@use "sass:list";
@use "sass:meta";
@use "sass:string";

@function core($selector) {
	@return ".#{$selector}";
}
@function hover($selector) {
	@return ".hover\\:#{$selector}:hover";
}
@function focus($selector) {
	@return ".focus\\:#{$selector}:focus";
}
@function touch($selector) {
	@return ".touch\\:#{$selector}:hover, .touch\\:#{$selector}:focus";
}
@function group-hover($selector) {
	@return ".group:hover .group-hover\\:#{$selector}";
}
@function group-focus($selector) {
	@return ".group:focus .group-focus\\:#{$selector}";
}
@function group-touch($selector) {
	@return ".group:hover .group-touch\\:#{$selector}, .group:focus .group-touch\\:#{$selector}";
}
@function responsive($selector) {
	@return "#{&}#{$selector}";
}

@function str-declass($selector) {
    $str-selector: "" + $selector;
    @return string.slice($str-selector, 2);
}

// Ex:
//
// .bg-red-500 { ... }
// .hover\:bg-red-500:hover { ... }
// .focus\:bg-red-500:focus { ... }
//
@mixin -impl-development($ampersand, $variants...) {
    @each $variant in $variants {
        #{meta.call($variant, str-declass($ampersand))} {
            @content;
        }
    }
}

// Ex:
//
// .bg-red-500,
// .hover\:bg-red-500:hover,
// .focus\:bg-red-500:focus { ... }
//
@mixin -impl-production($ampersand, $variants...) {
    $selector: "";
    @each $variant in $variants {
       $selector: $selector + if($selector == "", "", ", ") + meta.call($variant, str-declass($ampersand));
    }
    #{$selector} {
        @content;
    }
}

@mixin variants($variants) {
    @if list.length($variants) == 0 {
        $variants: (core,);
    }
    @at-root {
        @if $env == development {
            @include -impl-development(&, $variants...) {
                @content;
            }
        } @else if $env == production {
            @include -impl-production(&, $variants...) {
                @content;
            }
        }
    }
}

// Ex:
//
// @include compose($variants) using ($v) {
//   .bg-red-400 { @include variants($v) { ... } }
//   .bg-red-400 { @include variants($v) { ... } }
//   .bg-red-600 { @include variants($v) { ... } }
// }
//
// -> .bg-red-400 { ... }
// -> .bg-red-400 { ... }
// -> .bg-red-600 { ... }
// -> .hover\:bg-red-400:hover { ... }
// -> .hover\:bg-red-400:hover { ... }
// -> .hover\:bg-red-600:hover { ... }
//
@mixin compose($variants) {
    @if $env == development {
        @each $variant in $variants {
            @content ($variant);
        }
    } @else if $env == production {
        @content ($variants);
    }
}

$env: development;

$my-variants: (core, hover, focus);

@include compose($my-variants) using ($composed) {
    .a {
        @include variants($composed) {
            content: "Hello, world!";
        }
    }
    .b {
        @include variants($composed) {
            content: "Hello, world!";
        }
    }
}
```
