### ISSUE TITLE
[Todo] If we use HEXA as a format we can save on bytes for colors

### ISSUE THREAD

**Issue by zaydek** [zaydek/duomo#241]
This should actually be a meaningful deduction for `duomo.css`.

**Comment by zaydek** [comment]
See https://gitter.im/sass/sass?at=5ff096c3e7f693041f479a38.

**Comment by zaydek** [comment]
We basically have to choose between HSLA or RGBA for the alpha case. Technically for non-alpha colors we can use RGBA to save on bytes, but that makes this more complicated because they we optimize for multiple color spaces which is weird.  We can stick to our HSLA approach for now.

**Comment by zaydek** [comment]
Current implementation:

```scss
// Ex:
//
// hex-to-raw-hsl((white: #fff, black: #000))
// -> (white: hsl(0deg, 0%, 100%), black: hsl(0deg, 0%, 0%))
//
// TODO: This function should be generalized enough to work for any color space.
// For example: RGB, RGBA, HSL, HSLA, HEX, and HEXA.
//
// In theory, this already happens due to the nature of Sass. This should be
// tested for regardless.
//
// For more context, see:
//
// - https://github.com/zaydek/duomo/issues/241
// - https://gitter.im/sass/sass?at=5ff096c3e7f693041f479a38
//
@function hex-to-raw-hsl($hex) {
	@if $hex == transparent or $hex == currentColor {
		@return $hex;
	}
	// prettier-ignore
	$raw-hsl: (
		math.round(color.hue($hex)),
		math.round(color.saturation($hex)),
		math.round(color.lightness($hex)),
	);
	@return $raw-hsl;
}

```
