### ISSUE TITLE
[Todo] Add hide md:show classes

### ISSUE THREAD

**Issue by zaydek** [zaydek/duomo#97]
The problem with `hidden ...` is that it cares about `display` but we want to think at a higher level of ‘is this on, is this off?’ without worrying about `hstack vstack grid` etc. So what we could do is have something like:

```
.hide {
  display: none;
}
.show {
  display: var(--duomo-display, block);
}
```

Then all display utilities can hook into `duomo-display` like `hstack vstack grid` to update show.

The shorter name `hide` versus `hidden` is more active, the same way `round` is more active than `rounded`.

**Comment by zaydek** [comment]
Working implementation:

```scss
@function get-ampersand() {
	@if not & {
		@return ".";
	}
	@return & + "\\:";
}

@mixin thing {
	$amp: get-ampersand();

	#{$amp}hide {
		display: none;
	}
	#{$amp}show {
		display: var(--duomo-display);
	}

	#{$amp}hstack {
		--duomo-display: flex;
	}
	#{$amp}vstack {
		--duomo-display: flex;
	}
}
```
