### ISSUE TITLE
[Todo] Separate complex definitions

### ISSUE THREAD

**Issue by zaydek** [zaydek/duomo#98]
We have some complex definitions to account for things like `[style*=...]`. These work but can clutter dev tools. What we can do is make sure such rules are written separately so only the relevant rule is shown in dev tools. The counter argument here is that it may be harder to understand *why* some behavior is active.

**Comment by zaydek** [comment]
Since we deprecated `up` and `down` this argument doesn’t apply in general. That being said `width` overrides for stacks may or may not violate this rule.

**Comment by zaydek** [comment]
We can close this since:

```scss
@each $v in $range {
	#{$amp}w-#{$v} {
		width: resolve($v, $resolver);
		[class*="hstack"] > & {
			flex-shrink: 0;
		}
	}
}
```

Generates two discrete classes. Nesting was only for formatting.
